SUMMARY = "A Modbus library"
DESCRIPTION = "libmodbus is a C library designed to provide a fast and robust implementation of the Modbus protocol. It runs on Linux, Mac OS X, FreeBSD, QNX, and Windows."
HOMEPAGE = "https://libmodbus.org"
SECTION = "libs"
LICENSE = "LGPL-2.1+"
LIC_FILES_CHKSUM = "file://COPYING.LESSER;md5=4fbd65380cdd255951079008b364516c"

SRC_URI = "https://github.com/stephane/libmodbus/releases/download/v${PV}/libmodbus-${PV}.tar.gz"
